# Generated by Django 3.1.4 on 2021-01-25 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_title', models.CharField(max_length=100)),
                ('author_born_date', models.CharField(max_length=100)),
                ('author_born_location', models.CharField(max_length=200)),
                ('author_description', models.TextField()),
            ],
            options={
                'ordering': ['author_title', 'author_description'],
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraping.authors')),
            ],
            options={
                'ordering': ['author'],
            },
        ),
    ]
