# Generated by Django 3.1.4 on 2021-01-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'ordering': ['author_title', 'author_description'], 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='quotes',
            options={'ordering': ['author'], 'verbose_name_plural': 'Quotes'},
        ),
    ]
