# Generated by Django 3.1.4 on 2021-01-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20210120_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_sending', models.DateTimeField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
