# Generated by Django 3.1.4 on 2021-01-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_sendemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendEmail',
        ),
    ]
