# Generated by Django 3.1.4 on 2021-01-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_objectstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizationrate',
            name='type',
            field=models.CharField(max_length=400),
        ),
    ]
