# Generated by Django 3.1.4 on 2021-01-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20210119_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectstable',
            old_name='timestamp',
            new_name='data_update',
        ),
        migrations.AddField(
            model_name='objectstable',
            name='data_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
