# Generated by Django 3.1.4 on 2021-01-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20210121_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectstable',
            name='object_info',
            field=models.CharField(db_column='Information', max_length=1000),
        ),
    ]
