# Generated by Django 3.1.4 on 2021-01-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20210121_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectstable',
            name='object_info',
            field=models.TextField(db_column='Information'),
        ),
    ]
