# Generated by Django 3.1.4 on 2021-01-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20210121_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectstable',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
