# Generated by Django 3.1.4 on 2021-01-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_objectstable_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectstable',
            old_name='type',
            new_name='object_type',
        ),
    ]
